version: '3.9'

services:
    client:
      container_name: client
      restart: always
      build: ./client
      ports:
        - "3000:3000"
      links:
        - server
    server:
      container_name: server
      restart: always
      build: ./server
      ports:
        - "4000:4000"
      